[package]
name = "clsag"
version = "0.1.0"
authors = ["kev <decentralisedkev@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { version = "1.0.3", features = ["serde"] }
rand = "0.6"
sha2 = "0.8"
merlin = "1.1"